name: agents_boardroom
description: Premium community platform for estate agents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.2.10  # if you're using messaging
  firebase_analytics: ^11.5.0  # if you're using analytics
  
  # UI & Animations (reduced for performance)
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  table_calendar: ^3.0.9
  
  # Navigation
  go_router: ^16.0.0
  
  # Utils
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  url_launcher: ^6.2.1
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  
  # Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Network
  dio: ^5.3.3
  connectivity_plus: ^6.1.4
  
  # Payment
  flutter_stripe: ^11.5.0
  
  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Utilities
  intl: ^0.20.2
  timeago: ^3.5.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  
  # Icons & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
    
 