// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeyrvLWesfkAHFRdEO8oRHOxVF-CK3N_g',
    appId: '1:175824949980:web:4c7343b2fb2b78b6501a19',
    messagingSenderId: '175824949980',
    projectId: 'boardroomagent',
    authDomain: 'boardroomagent.firebaseapp.com',
    storageBucket: 'boardroomagent.firebasestorage.app',
    measurementId: 'G-XS8ZKEQKSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwZeffVPFF9ASW5WZQvWWoPLvsJNzBxw',
    appId: '1:175824949980:android:a5c34a534ca8f58c501a19',
    messagingSenderId: '175824949980',
    projectId: 'boardroomagent',
    storageBucket: 'boardroomagent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSV0nss2quBRoCrgQCj_22MhhOXPUhIw',
    appId: '1:175824949980:ios:83f0909173f7d6d1501a19',
    messagingSenderId: '175824949980',
    projectId: 'boardroomagent',
    storageBucket: 'boardroomagent.firebasestorage.app',
    iosBundleId: 'com.example.agentsBoardroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmSV0nss2quBRoCrgQCj_22MhhOXPUhIw',
    appId: '1:175824949980:ios:83f0909173f7d6d1501a19',
    messagingSenderId: '175824949980',
    projectId: 'boardroomagent',
    storageBucket: 'boardroomagent.firebasestorage.app',
    iosBundleId: 'com.example.agentsBoardroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeyrvLWesfkAHFRdEO8oRHOxVF-CK3N_g',
    appId: '1:175824949980:web:25e54292602f61db501a19',
    messagingSenderId: '175824949980',
    projectId: 'boardroomagent',
    authDomain: 'boardroomagent.firebaseapp.com',
    storageBucket: 'boardroomagent.firebasestorage.app',
    measurementId: 'G-98QQ6PX4KV',
  );
}
